# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:node_version
  - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn run test-ie

# Don't actually build.
build: off

matrix:
  fast_finish: true

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
